export const MSG_ADD_TO_CART_SUCCESS = 'PURCHASE SUCCESS!';
export const MSG_ADD_TO_CART_FAILED = 'PURCHASE FAILED!'
export const MSG_UPDATE_CART_SUCCESS = 'UPDATE SUCCESS!'
export const MSG_UPDATE_CART_FAILED = 'UPDATE FAILED!'
export const MSG_DELETE_CART_SUCCESS = 'DELETE SUCCESS!'
export const MSG_DELETE_CART_FAILED = 'DELETE FAILED!'
export const MSG_CART_EMPTY = 'CART EMPTY!'
export const MSG_WELCOME = 'HAPPY SHOPPING ONLINE!'